<a href="https://colab.research.google.com/github/evonyava/KSVD_Yakovliev_FIT_3-8/blob/main/%D0%9B%D0%91_1_%D0%AF%D0%BA%D0%BE%D0%B2%D0%BB%D1%94%D0%B2_%D0%A4%D0%86%D0%A2_4_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

In [ ]:
import numpy as np
from numpy.linalg import norm
from numpy.linalg import matrix_power
from numpy.linalg import matrix_rank

In [ ]:
## Завдання 1. Додавання, віднімання та множення векторів на число

# Ініціалізація векторів
a = np.array([7, -2, 5, 9])
b = np.array([3, 6, -1, 4])

# 1. Знайти a + b
res_add = a + b
print("1. a + b =", res_add)

# 2. Знайти a - b
res_sub = a - b
print("2. a - b =", res_sub)

# 3. Помножити вектор a на число 4
res_mul_a = a * 4
print("3. a * 4 =", res_mul_a)

# 4. Помножити вектор b на число -2
res_mul_b = b * -2
print("4. b * -2 =", res_mul_b)

# 5. Обчислити поелементний добуток a * b
res_mul_ab = a * b
print("5. a * b =", res_mul_ab)

1. a + b = [10  4  4 13]
2. a - b = [ 4 -8  6  5]
3. a * 4 = [28 -8 20 36]
4. b * -2 = [ -6 -12   2  -8]
5. a * b = [ 21 -12  -5  36]


In [ ]:
## Завдання 2. Скалярний добуток і довжина векторів
# Ініціалізація векторів
u = np.array([2, -3, 6])
v = np.array([5, 1, 4])

# 1. Скалярний добуток двома способами
dot_1 = np.dot(u, v)
dot_2 = u @ v
print(f"1. Скалярний добуток (np.dot): {dot_1}")
print(f"   Скалярний добуток (@): {dot_2}")

# 2. Евклідова норма (довжина) векторів
norm_u = norm(u)
norm_v = norm(v)
print(f"\n2. Евклідова норма вектора u: {norm_u}")
print(f"   Евклідова норма вектора v: {norm_v:.2f}")

# 3. Косинус кута між векторами
cos_theta = dot_1 / (norm_u * norm_v)
print(f"\n3. Косинус кута між векторами: {cos_theta:.3f}")

1. Скалярний добуток (np.dot): 31
   Скалярний добуток (@): 31

2. Евклідова норма вектора u: 7.0
   Евклідова норма вектора v: 6.48

3. Косинус кута між векторами: 0.683


In [ ]:
## Завдання 3. Основні дії з матрицями


# Ініціалізація матриць
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])

# 1. Обчислення A + B
res_add = A + B
print("1. A + B:\n", res_add)

# 2. Обчислення A - B
res_sub = A - B
print("\n2. A - B:\n", res_sub)

# 3. Поелементний добуток A * B
res_mul_ab = A * B
print("\n3. Поелементний добуток A * B:\n", res_mul_ab)

# 4. Множення матриці A на число 5
res_mul_5 = A * 5
print("\n4. Матриця A * 5:\n", res_mul_5)

# 5. Транспонована матриця A (можна використати A.T або np.transpose(A))
res_transposed = A.T
print("\n5. Транспонована матриця A:\n", res_transposed)

1. A + B:
 [[4 3 5]
 [9 3 6]]

2. A - B:
 [[ 2  7 -7]
 [-5 -3  2]]

3. Поелементний добуток A * B:
 [[  3 -10  -6]
 [ 14   0   8]]

4. Матриця A * 5:
 [[15 25 -5]
 [10  0 20]]

5. Транспонована матриця A:
 [[ 3  2]
 [ 5  0]
 [-1  4]]


In [ ]:
## Завдання 4. Матричне множення


# Ініціалізація матриць
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

# 1. Матричний добуток
C = A @ B

# 2. Форма результату
shape_C = C.shape

# 3. Обчислення елемента [0, 1] вручну
row_0_A = A[0, :]  # 0-й рядок матриці A: [2, 1, 3]
col_1_B = B[:, 1]  # 1-й стовпець матриці B: [2, 0, 1]
manual_element = np.dot(row_0_A, col_1_B)

print("1. A @ B =\n", C)
print(f"2. Форма результату: {shape_C}")
print(f"3. Елемент [0, 1] вручну: {manual_element}")

1. A @ B =
 [[17  7]
 [32  5]]
2. Форма результату: (2, 2)
3. Елемент [0, 1] вручну: 7


In [ ]:
## Завдання 5. Циклічний зсув вектора


# Ініціалізація вектора
v = np.array([12, 7, 19, 4, 11, 8])

# 1. Циклічний зсув на 2 позиції вправо (додатне значення зсуву)
v_right = np.roll(v, 2)
print("1. Зсув на 2 вправо:  ", v_right)

# 2. Циклічний зсув на 3 позиції вліво (від'ємне значення зсуву)
v_left = np.roll(v, -3)
print("2. Зсув на 3 вліво:   ", v_left)

# 3. Відновлення початкового вектора із результату першого зсуву
# (для компенсації зсуву на 2 вправо, потрібно зсунути на 2 вліво)
v_restored = np.roll(v_right, -2)
print("3. Відновлений вектор:", v_restored)

1. Зсув на 2 вправо:   [11  8 12  7 19  4]
2. Зсув на 3 вліво:    [ 4 11  8 12  7 19]
3. Відновлений вектор: [12  7 19  4 11  8]


In [ ]:
## Завдання 6. Сортування та індекси


# Ініціалізація вектора
v = np.array([42, 17, 29, 8, 35, 23])

# 1. Сортування за зростанням
v_asc = np.sort(v)
print("1. За зростанням:", v_asc)

# 2. Сортування за спаданням (шляхом обернення відсортованого масиву)
v_desc = np.sort(v)[::-1]
print("2. За спаданням: ", v_desc)

# 3. Індекси для сортування за спаданням
# np.argsort(v) дає індекси за зростанням, тому обертаємо їх [::-1]
indices_desc = np.argsort(v)[::-1]
print("3. Індекси (від найбільшого до найменшого):", indices_desc)

1. За зростанням: [ 8 17 23 29 35 42]
2. За спаданням:  [42 35 29 23 17  8]
3. Індекси (від найбільшого до найменшого): [0 4 2 5 1 3]


In [ ]:
## Завдання 7. Обмеження значень

# Ініціалізація вектора
v = np.array([-12, -4, 3, 18, 27, 35, 48])

# 1. Обмеження значень діапазоном [-5, 30]
v_clipped = np.clip(v, -5, 30)

# 2. Визначення індексів змінених елементів
# Знаходимо елементи, які не дорівнюють своїм початковим значенням
changed_indices = np.where(v != v_clipped)[0]

print("Обмежений вектор:", v_clipped)
print("Індекси змінених елементів:", changed_indices)

Обмежений вектор: [-5 -4  3 18 27 30 30]
Індекси змінених елементів: [0 5 6]


In [ ]:
## Завдання 8. Унікальні значення та частоти

# Ініціалізація вектора
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

# 1 та 2. Знаходження унікальних значень та їхніх частот
unique_values, counts = np.unique(v, return_counts=True)
print("1. Унікальні значення:", unique_values)
print("2. Кількість появ:    ", counts)

# 3. Визначення найчастішого значення
# np.argmax знаходить індекс найбільшого елемента в масиві частот
most_frequent_index = np.argmax(counts)
most_frequent_value = unique_values[most_frequent_index]

print(f"3. Найчастіше значення: {most_frequent_value} (трапляється {counts[most_frequent_index]} рази)")

1. Унікальні значення: [2 4 7 9]
2. Кількість появ:     [3 3 4 1]
3. Найчастіше значення: 7 (трапляється 4 рази)


In [ ]:
## Завдання 9. Поворот матриці
# Ініціалізація матриці
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

# 1. Поворот на 90° за годинниковою стрілкою (k=-1)
rot_90_cw = np.rot90(A, k=-1)

# 2. Поворот на 180° (k=2)
rot_180 = np.rot90(A, k=2)

# 3. Поворот на 90° проти годинникової стрілки (k=1, за замовчуванням)
rot_90_ccw = np.rot90(A, k=1)

print("1. Поворот на 90° за годинниковою стрілкою:\n", rot_90_cw)
print("\n2. Поворот на 180°:\n", rot_180)
print("\n3. Поворот на 90° проти годинникової стрілки:\n", rot_90_ccw)

1. Поворот на 90° за годинниковою стрілкою:
 [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

2. Поворот на 180°:
 [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

3. Поворот на 90° проти годинникової стрілки:
 [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


In [ ]:
## Завдання 10. Додавання рамки до матриці

# Ініціалізація матриці
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

# 1. Рамка шириною 1 елемент, заповнена значенням -1
A_pad_1 = np.pad(A, pad_width=1, mode='constant', constant_values=-1)

# 2. Рамка шириною 2 елементи, заповнена нулями
A_pad_2 = np.pad(A, pad_width=2, mode='constant', constant_values=0)

print("1. Матриця з рамкою (-1):\n", A_pad_1)
print("   Форма отриманої матриці:", A_pad_1.shape)

print("\n2. Матриця з рамкою (0):\n", A_pad_2)
print("   Форма отриманої матриці:", A_pad_2.shape)

1. Матриця з рамкою (-1):
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
   Форма отриманої матриці: (5, 5)

2. Матриця з рамкою (0):
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
   Форма отриманої матриці: (7, 7)


In [ ]:
## Завдання 11. Перестановка рядків і стовпців

# Ініціалізація матриці та масивів перестановок
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

# 1. Перестановка рядків
A_rows_reordered = A[row_order, :]

# 2. Перестановка стовпців
A_shuffled = A_rows_reordered[:, col_order]

print("1. Матриця після перестановки рядків:\n", A_rows_reordered)
print("\n2. Матриця після перестановки стовпців (фінальна перемішана):\n", A_shuffled)

# 3. Відновлення початкової матриці
# Знаходимо обернені перестановки за допомогою np.argsort()
inv_row_order = np.argsort(row_order)
inv_col_order = np.argsort(col_order)

# Відновлюємо стовпці, потім рядки (або навпаки, порядок не має значення для незалежних осей)
A_restored = A_shuffled[:, inv_col_order][inv_row_order, :]

print("\n3. Обернена перестановка рядків (індекси):", inv_row_order)
print("   Обернена перестановка стовпців (індекси):", inv_col_order)
print("   Відновлена матриця:\n", A_restored)

1. Матриця після перестановки рядків:
 [[31 32 33 34]
 [11 12 13 14]
 [41 42 43 44]
 [21 22 23 24]]

2. Матриця після перестановки стовпців (фінальна перемішана):
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

3. Обернена перестановка рядків (індекси): [1 3 0 2]
   Обернена перестановка стовпців (індекси): [2 1 3 0]
   Відновлена матриця:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [ ]:
## Завдання 12. Трикутні частини матриці

# Ініціалізація матриці
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

# 1. Верхня трикутна частина (з головною діагоналлю)
upper_tri = np.triu(A)

# 2. Нижня трикутна частина (з головною діагоналлю)
lower_tri = np.tril(A)

# 3. Строго верхня та строго нижня частини (без діагоналі)
# k=1 зсуває діагональ на 1 вгору, k=-1 зсуває на 1 вниз
strictly_upper = np.triu(A, k=1)
strictly_lower = np.tril(A, k=-1)

# 4. Відновлення початкової матриці
# (нижня частина з діагоналлю + строго верхня частина)
reconstructed_A = lower_tri + strictly_upper

print("1. Верхня трикутна частина:\n", upper_tri)
print("\n2. Нижня трикутна частина:\n", lower_tri)
print("\n3. Строго верхня частина:\n", strictly_upper)
print("\n   Строго нижня частина:\n", strictly_lower)
print("\n4. Відновлена матриця:\n", reconstructed_A)

1. Верхня трикутна частина:
 [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

2. Нижня трикутна частина:
 [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

3. Строго верхня частина:
 [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

   Строго нижня частина:
 [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

4. Відновлена матриця:
 [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]


In [ ]:
## Завдання 13. Зовнішній добуток векторів

# Ініціалізація векторів
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

# 1. Зовнішній добуток
outer_product = np.outer(a, b)

# 2. Форма матриці
shape_outer = outer_product.shape

# 3. Перевірка елемента [2, 1]
element_matrix = outer_product[2, 1]
element_manual = a[2] * b[1]

print("1. Матриця зовнішнього добутку:\n", outer_product)
print(f"\n2. Форма отриманої матриці: {shape_outer}")
print(f"\n3. Елемент [2, 1] у матриці: {element_matrix}")
print(f"   Ручне обчислення a[2] * b[1]: {element_manual}")

1. Матриця зовнішнього добутку:
 [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]

2. Форма отриманої матриці: (4, 3)

3. Елемент [2, 1] у матриці: 35
   Ручне обчислення a[2] * b[1]: 35


In [ ]:
## Завдання 14. Добуток Кронекера

# Ініціалізація матриць
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

# 1. Добуток Кронекера A і B
kron_AB = np.kron(A, B)

# 2. Добуток Кронекера B і A
kron_BA = np.kron(B, A)

print("1. Добуток Кронекера np.kron(A, B):\n", kron_AB)
print("   Форма:", kron_AB.shape)

print("\n2. Добуток Кронекера np.kron(B, A):\n", kron_BA)
print("   Форма:", kron_BA.shape)

# 3. Порівняння матриць (чи рівні вони)
are_equal = np.array_equal(kron_AB, kron_BA)
print(f"\n3. Чи рівні матриці? {are_equal}")

1. Добуток Кронекера np.kron(A, B):
 [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]
   Форма: (4, 4)

2. Добуток Кронекера np.kron(B, A):
 [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]
   Форма: (4, 4)

3. Чи рівні матриці? False


In [ ]:
## Завдання 15. Комутатор двох матриць

# Перша пара матриць
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

# Друга пара матриць
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

# 1. Обчислення комутаторів [A, B] = AB - BA
commutator_1 = (A1 @ B1) - (B1 @ A1)
commutator_2 = (A2 @ B2) - (B2 @ A2)

print("Комутатор першої пари [A1, B1]:\n", commutator_1)
print("\nКомутатор другої пари [A2, B2]:\n", commutator_2)

# 2. Перевірка комутативності (AB = BA, або [A, B] = 0) за допомогою np.allclose()
is_commutative_1 = np.allclose(A1 @ B1, B1 @ A1)
# Або можна перевірити чи дорівнює комутатор нулю: np.allclose(commutator_1, 0)

is_commutative_2 = np.allclose(A2 @ B2, B2 @ A2)

print(f"\nЧи виконується AB = BA для першої пари? {is_commutative_1}")
print(f"Чи виконується AB = BA для другої пари? {is_commutative_2}")

Комутатор першої пари [A1, B1]:
 [[0 0]
 [0 0]]

Комутатор другої пари [A2, B2]:
 [[ 0 -6]
 [-3  0]]

Чи виконується AB = BA для першої пари? True
Чи виконується AB = BA для другої пари? False


In [ ]:
## Завдання 16. Квадратична форма

# Ініціалізація матриці та векторів
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

# 1. Обчислення квадратичної форми для одного вектора (xᵀAx)
qf_single = x @ A @ x

# 2. Обчислення квадратичної форми для кожного рядка матриці X без циклів
# 'ni' — матриця X (n векторів довжини i)
# 'ij' — матриця A
# 'nj' — матриця X (n векторів довжини j)
# '->n' — результат: вектор довжини n, що містить суму для кожного рядка
qf_multiple = np.einsum('ni,ij,nj->n', X, A, X)

print("1. Квадратична форма xᵀAx:", qf_single)
print("2. Квадратичні форми для кожного вектора з X:", qf_multiple)

1. Квадратична форма xᵀAx: 35
2. Квадратичні форми для кожного вектора з X: [35 17 27]


In [ ]:
## Завдання 17. Степінь матриці

# Ініціалізація матриці
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

# 1. Обчислення A²
A_squared = matrix_power(A, 2)

# 2. Обчислення A³
A_cubed = matrix_power(A, 3)

# 3. Перевірка, що A³ = A² @ A
A_cubed_manual = A_squared @ A
is_equal = np.array_equal(A_cubed, A_cubed_manual)
# Або через np.allclose(A_cubed, A_cubed_manual)

print("1. Матриця A²:\n", A_squared)
print("\n2. Матриця A³:\n", A_cubed)
print(f"\n3. Чи збігається результат (A³ == A² @ A)? {is_equal}")

1. Матриця A²:
 [[1 2 1]
 [1 1 2]
 [2 1 1]]

2. Матриця A³:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]

3. Чи збігається результат (A³ == A² @ A)? True


In [ ]:
## Завдання 18. Ранг матриці

# Ініціалізація матриць
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

# 1. Знаходження рангу кожної матриці
rank_A = matrix_rank(A)
rank_B = matrix_rank(B)

print(f"1. Ранг матриці A: {rank_A}")
print(f"   Ранг матриці B: {rank_B}")

# 2. Визначення повного рангу
# Матриця 3x3 має повний ранг, якщо її ранг дорівнює 3
is_full_rank_A = rank_A == min(A.shape)
is_full_rank_B = rank_B == min(B.shape)

print(f"\n2. Чи має матриця A повний ранг? {is_full_rank_A}")
print(f"   Чи має матриця B повний ранг? {is_full_rank_B}")

1. Ранг матриці A: 3
   Ранг матриці B: 2

2. Чи має матриця A повний ранг? True
   Чи має матриця B повний ранг? False


In [ ]:
## Завдання 19. Власні значення та власні вектори


# Ініціалізація симетричної матриці
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

# 1. Знаходження власних значень (eigenvalues) та власних векторів (eigenvectors)
# Оскільки матриця симетрична, використовуємо np.linalg.eigh для кращої точності та продуктивності
eigenvalues, eigenvectors = np.linalg.eigh(A)

# 2. Перевірка співвідношення A @ V = V * λ
# Ліва частина: матричне множення матриці A на матрицю власних векторів V
left_side = A @ eigenvectors

# Права частина: поелементне множення (broadcasting) стовпців матриці V на вектор власних значень
right_side = eigenvectors * eigenvalues

# 3. Перевірка результату через np.allclose()
is_correct = np.allclose(left_side, right_side)

print("1. Власні значення (λ):", eigenvalues)
print("   Власні вектори (V):\n", eigenvectors)

print("\n2. Ліва частина (A @ V):\n", left_side)
print("   Права частина (V * λ):\n", right_side)

print(f"\n3. Чи виконується співвідношення (A @ V == V * λ)? {is_correct}")

1. Власні значення (λ): [2. 7.]
   Власні вектори (V):
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]

2. Ліва частина (A @ V):
 [[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]
   Права частина (V * λ):
 [[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]

3. Чи виконується співвідношення (A @ V == V * λ)? True


In [ ]:
## Завдання 20. Метод найменших квадратів

# Ініціалізація точок
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

# 1. Формування матриці ознак (стовпець одиниць та стовпець значень x)
X = np.column_stack([np.ones_like(x), x])

# 2. Знаходження коефіцієнтів a і b методом найменших квадратів
# rcond=None використовується для уникнення попереджень (FutureWarning) у нових версіях NumPy
coeffs, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)
a, b = coeffs

# 3. Обчислення прогнозних значень
y_pred = X @ coeffs

# 4. Знаходження суми квадратів залишків
# Можна взяти з результату lstsq (residuals[0]) або порахувати вручну
ssr = np.sum((y - y_pred)**2)

print("1. Матриця ознак X:\n", X)
print(f"\n2. Коефіцієнти: a = {a:.2f}, b = {b:.2f}")
print("\n3. Прогнозні значення y:\n", y_pred)
print(f"\n4. Сума квадратів залишків: {ssr:.4f}")

1. Матриця ознак X:
 [[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]

2. Коефіцієнти: a = 2.02, b = 2.01

3. Прогнозні значення y:
 [ 2.02  4.03  6.04  8.05 10.06]

4. Сума квадратів залишків: 0.1310
